// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  /// Web OAuth client ID from `google-services.json` (`client_type: 3`).
  static const String googleOAuthWebClientId =
      '680768531196-thtl79kon86oesjc155v513iipd0anv2.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name}.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnh7_5lFJWSO4oWFXBc2c-jjBrq3xwAs',
    appId: '1:680768531196:android:9a6c3b1320a899f0960579',
    messagingSenderId: '680768531196',
    projectId: 'meonmf-91753',
    storageBucket: 'meonmf-91753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkia1pLuRsbNQefz-0YVFXJGRjasVK2Lg',
    appId: '1:1077626154170:ios:6cf794b257a449804f6683',
    messagingSenderId: '1077626154170',
    projectId: 'stoxbox-5daa8',
    storageBucket: 'stoxbox-5daa8.appspot.com',
    iosClientId:
        '680768531196-thtl79kon86oesjc155v513iipd0anv2.apps.googleusercontent.com',
    iosBundleId: 'com.meon.kyc',
  );
}
