// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  /// Web OAuth client ID from `google-services.json` (`client_type: 3`).
  static const String googleOAuthWebClientId =
      '1077626154170-61kj6319g2tlhpig26uddesuio92d2oa.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name}.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3KYu4BOG5dmh0nI4BvAYoSiFm5aLR7c',
    appId: '1:1077626154170:android:dd3a513aef1bb4cc4f6683',
    messagingSenderId: '1077626154170',
    projectId: 'stoxbox-5daa8',
    storageBucket: 'stoxbox-5daa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkia1pLuRsbNQefz-0YVFXJGRjasVK2Lg',
    appId: '1:1077626154170:ios:6cf794b257a449804f6683',
    messagingSenderId: '1077626154170',
    projectId: 'stoxbox-5daa8',
    storageBucket: 'stoxbox-5daa8.appspot.com',
    iosClientId:
        '1077626154170-es9hivvnhu47uscieen8cgj8aq1afg7g.apps.googleusercontent.com',
    iosBundleId: 'com.bpwealth.stoxbox',
  );
}
